# Generated by Django 3.2.7 on 2021-11-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.BooleanField(default=False),
        ),
    ]
