# Generated by Django 3.2.3 on 2021-12-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_notion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notion',
        ),
    ]
